In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv')

In [6]:
df

,Date,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2/1/2008,19.5,22.4,15.6,6.2,0.0,W,41,S,SSW,...,92,84,1017.6,1017.4,8,8,20.7,20.9,Yes,Yes
1,2/2/2008,19.5,25.6,6.0,3.4,2.7,W,41,W,E,...,83,73,1017.9,1016.4,7,7,22.4,24.8,Yes,Yes
2,2/3/2008,21.6,24.5,6.6,2.4,0.1,W,41,ESE,ESE,...,88,86,1016.7,1015.6,7,8,23.5,23.0,Yes,Yes
3,2/4/2008,20.2,22.8,18.8,2.2,0.0,W,41,NNE,E,...,83,90,1014.2,1011.8,8,8,21.4,20.9,Yes,Yes
4,2/5/2008,19.7,25.7,77.4,4.8,0.0,W,41,NNE,W,...,88,74,1008.3,1004.8,8,8,22.5,25.5,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,6/21/2017,8.6,19.6,0.0,2.0,7.8,SSE,37,W,SSE,...,73,52,1025.9,1025.3,2,2,10.5,17.9,No,No
3267,6/22/2017,9.3,19.2,0.0,2.0,9.2,W,30,W,ESE,...,78,53,1028.5,1024.6,2,2,11.0,18.7,No,No
3268,6/23/2017,9.4,17.7,0.0,2.4,2.7,W,24,WNW,N,...,85,56,1020.8,1015.0,6,6,10.2,17.3,No,No
3269,6/24/2017,10.1,19.3,0.0,1.4,9.3,W,43,W,W,...,56,35,1017.3,1015.1,5,2,12.4,19.0,No,No
3270,6/25/2017,7.6,19.3,0.0,3.4,9.4,W,35,W,W,...,73,32,1018.6,1015.4,1,1,9.4,18.8,No,No

In [9]:
df=df.drop(['Date','WindDir9am','WindGustDir','WindDir3pm'] ,axis=1)

In [16]:
df

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,19.5,22.4,15.6,6.2,0.0,41,17,20,92,84,1017.6,1017.4,8,8,20.7,20.9,1,1
1,19.5,25.6,6.0,3.4,2.7,41,9,13,83,73,1017.9,1016.4,7,7,22.4,24.8,1,1
2,21.6,24.5,6.6,2.4,0.1,41,17,2,88,86,1016.7,1015.6,7,8,23.5,23.0,1,1
3,20.2,22.8,18.8,2.2,0.0,41,22,20,83,90,1014.2,1011.8,8,8,21.4,20.9,1,1
4,19.7,25.7,77.4,4.8,0.0,41,11,6,88,74,1008.3,1004.8,8,8,22.5,25.5,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3266,8.6,19.6,0.0,2.0,7.8,37,22,20,73,52,1025.9,1025.3,2,2,10.5,17.9,0,0
3267,9.3,19.2,0.0,2.0,9.2,30,20,7,78,53,1028.5,1024.6,2,2,11.0,18.7,0,0
3268,9.4,17.7,0.0,2.4,2.7,24,15,13,85,56,1020.8,1015.0,6,6,10.2,17.3,0,0
3269,10.1,19.3,0.0,1.4,9.3,43,17,19,56,35,1017.3,1015.1,5,2,12.4,19.0,0,0
3270,7.6,19.3,0.0,3.4,9.4,35,13,13,73,32,1018.6,1015.4,1,1,9.4,18.8,0,0

In [17]:
df.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [18]:
X=df[['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday']].values

In [19]:
X[0:5]

array([[1.9500e+01, 2.2400e+01, 1.5600e+01, 6.2000e+00, 0.0000e+00,
        4.1000e+01, 1.7000e+01, 2.0000e+01, 9.2000e+01, 8.4000e+01,
        1.0176e+03, 1.0174e+03, 8.0000e+00, 8.0000e+00, 2.0700e+01,
        2.0900e+01, 1.0000e+00],
       [1.9500e+01, 2.5600e+01, 6.0000e+00, 3.4000e+00, 2.7000e+00,
        4.1000e+01, 9.0000e+00, 1.3000e+01, 8.3000e+01, 7.3000e+01,
        1.0179e+03, 1.0164e+03, 7.0000e+00, 7.0000e+00, 2.2400e+01,
        2.4800e+01, 1.0000e+00],
       [2.1600e+01, 2.4500e+01, 6.6000e+00, 2.4000e+00, 1.0000e-01,
        4.1000e+01, 1.7000e+01, 2.0000e+00, 8.8000e+01, 8.6000e+01,
        1.0167e+03, 1.0156e+03, 7.0000e+00, 8.0000e+00, 2.3500e+01,
        2.3000e+01, 1.0000e+00],
       [2.0200e+01, 2.2800e+01, 1.8800e+01, 2.2000e+00, 0.0000e+00,
        4.1000e+01, 2.2000e+01, 2.0000e+01, 8.3000e+01, 9.0000e+01,
        1.0142e+03, 1.0118e+03, 8.0000e+00, 8.0000e+00, 2.1400e+01,
        2.0900e+01, 1.0000e+00],
       [1.9700e+01, 2.5700e+01, 7.7400e+01, 4.8000e+00, 0.0000e+00,
        4.1000e+01, 1.1000e+01, 6.0000e+00, 8.8000e+01, 7.4000e+01,
        1.0083e+03, 1.0048e+03, 8.0000e+00, 8.0000e+00, 2.2500e+01,
        2.5500e+01, 1.0000e+00]])

In [20]:
y=df['RainTomorrow']

In [21]:
y[0:5]

0    1
1    1
2    1
3    1
4    1
Name: RainTomorrow, dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le=LabelEncoder()
col=['RainToday','RainTomorrow']
df[col]=df[col].apply(LabelEncoder().fit_transform)

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)

In [26]:
print("Training data shape ",X_train.shape)
print("Testing data shape ",X_test.shape)

Training data shape  (2616, 17)
Testing data shape  (655, 17)

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
k=4
neigh=KNeighborsClassifier(n_neighbors=k).fit(X_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=4)

In [29]:
y_hat=neigh.predict(X_test)

In [30]:
y_hat[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0])

In [31]:
y_test[0:10]

229     0
2347    1
1783    0
3030    0
1651    1
3012    0
2027    0
2568    0
2465    1
1725    0
Name: RainTomorrow, dtype: int64

In [32]:
from sklearn import metrics

In [34]:
print("The training accuracy is ",metrics.accuracy_score(y_train,neigh.predict(X_train)))

The training accuracy is  0.8570336391437309

In [35]:
print("The testing accuracy is ",metrics.accuracy_score(y_hat,y_test))

The testing accuracy is  0.8213740458015267

In [43]:
accuracy=[]
for i in range(1,11):
    neigh=KNeighborsClassifier(n_neighbors=i).fit(X_train,y_train)
    y_hat=neigh.predict(X_test)
    accuracy.append(metrics.accuracy_score(y_hat,y_test))

In [44]:
print(accuracy)

[0.7740458015267175, 0.7893129770992366, 0.8030534351145038, 0.8213740458015267, 0.8274809160305343, 0.8137404580152672, 0.8259541984732824, 0.8229007633587786, 0.8274809160305343, 0.8305343511450382]

In [46]:
x=max(accuracy)
k=1
for i in accuracy:
    if(i==x):
        break
    else:
        k+=1
print("The accuracy of the model is ",x, 'with the value of K = ',k)

The accuracy of the model is  0.8305343511450382 with the value of K =  10